name: Deploy Next.js Application

on:
  push:
    branches:
      - dev
    
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync Code to Server
        run: |
          rsync -avz --delete \
            -e "ssh \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -p ${{ secrets.SERVER_PORT }}" \
            --exclude ".git" \
            --exclude ".github" \
            --exclude "node_modules" \
            ./ \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/ubuntu/dev_app/

      - name: Deploy Application
        run: |
          ssh \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -p ${{ secrets.SERVER_PORT }} \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'

            set -e

            cd /home/ubuntu/dev_app
          
            echo "building the docker image"

            docker build -t application:dev .
            echo "Starting application..."
            docker compose up -d

           

            echo "Deployment completed successfully!"

          EOF

      - name: Reload Nginx
        run: |
          ssh \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -p ${{ secrets.SERVER_PORT }} \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
            "sudo nginx -t && sudo systemctl reload nginx"
